name: Pallab-Excloud Deploy
on:
  push:
    branches:
      - main
jobs:
  # first connect with the server suing host and username and sshkey
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 210.79.129.141
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          # uncomment this if you don't want to use docker for ci/cd
          # script: |
          #   cd /home/ubuntu/pallab/test-depoyment-excloud-demo
          #   git pull origin main
          #   npm install
          #   pm2 restart pallab-server

          script: |
            cd /home/ubuntu/pallab
            sudo docker pull pallabdev/pallab-base:latest
            sudo docker stop pallab-server || true
            sudo docker rm pallab-server || true
            sudo docker run -d --name pallab-server -p 3000:3000 pallabdev/pallab-base:latest
